import { Nunito } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { dbConnect } from "@/services/mongo";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const conn = await dbConnect();

  return (
    <html lang="en">
      <body className={nunito.className}>
        {children}
        <ToastContainer position="top-right" />
      </body>
    </html>
  );
}
